.TH rsmy 1 "04/03/2023" "v0.02"
.SH NAME
Rosemary (rsmy) - a simple programming language
.SH SYNOPSIS
.B [ --help ] [ --update ] [
.I filename ]
.SH DESCRIPTION
.B Rosemary
is a simple yet powerful programming language. The idea is to take the usability of
Python, yet the low-level access of C. We also took curly bracket syntax, to allow
for more simple programming styles. rsmy is not hard to learn. It is very similar
syntactically to C, PHP and Python, and can be learned in a weekend. It can however
be very powerful, used in a variety of contexts helped by its ability to run C++ code
right in your rsmy code.

.PP
.B To use:
run rsmy on its own to launch an interactive shell
or run 
.B rsmy [ filename ] 
to launch and run the file provided.
